[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_custom = "2cazkdWKXoKgUUcPygLZ9Ty1iwL2qCdGXY9m7mZV1iDp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\dhana\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
